  # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: project cicd flow

on:
  push:
    branches: [ "master" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven


      env:
        AWS_REGION: ap-south-1
        ECR_REPOSITORY: repo/github-actions
#        CONTAINER_NAME: containerName

#
#    - name: Build Project
#      run: bash scm/build.sh
#      working-directory: github-actions-example
#
#    - name: Run Tests
#      run: bash scm/test.sh
#      working-directory: github-actions-example
#
#    - name: Analyze with Sonarcloud
#      run: mvn clean verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}


#    - name: Login DockerHub
#      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Run CI/CD Script
      working-directory: github-actions-example
      env:
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Add this for SonarCloud/PR features
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      run: bash scm/txt.sh

  #    - name: Deploy Application
  #      shell: bash
  #      env:
  #        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #      run: bash scm/deploy.sh
  #      working-directory: github-actions-example